#!/bin/bash
#SBATCH --job-name=dsa_aug_test
#SBATCH --partition dept.appliedmath
#SBATCH --output=/home/akaur101/data/sp26/rgc/outputs/dsa_test_resamp_%j.stdout

#SBATCH --gres=gpu:1
#SBATCH --time=5:00:00

#SBATCH --mail-user=akaur101@ucmerced.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=ALL
#SBATCH --export=ALL

module load anaconda3
source activate env_pytorch
python /home/akaur101/data/sp26/rgc/dsa_test_resamp.py  /home/akaur101/data/dsa_images/raw  /home/akaur101/data/dsa_images/gt $1


